# Generated by Django 2.1.3 on 2018-11-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150, verbose_name='course_name')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last_name')),
                ('phone', models.CharField(max_length=12, verbose_name='phone')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='date_pub')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requestApp.Course', verbose_name='Course')),
            ],
        ),
    ]
